Iter23 - graceful shutdown
SerjRamone/metrius pull request #23
Opened 2024-04-01 09:04 UTC by SerjRamone

2024-04-07 11:39 UTC, s-shpak requested changes

2024-04-07 11:39 UTC, s-shpak commented on cmd/agent/main.go
> +			return
Программа должна завершиться с ошибкой здесь. Для этого можно использовать `log.Fatal`

2024-04-07 11:39 UTC, s-shpak commented on internal/config/config.go
> +		return err
Ошибки из внешних пакетов стоит оборачивать

2024-04-07 11:39 UTC, s-shpak commented on internal/config/config.go
> +				return errTypeAssertion
Здесь сообщение об ошике стоит сделать более подробным

2024-04-07 11:39 UTC, s-shpak commented on internal/config/config.go
> +		if param == "poll_interval" && c.PollInterval == agentDefaultPollInterval {
Может быть эту часть кода можно как-то объединить с предыдущей, чтобы не дуплицировать слишком много кода ?

2024-04-07 11:39 UTC, s-shpak commented on internal/middlewares/crypto.go
> +			bodyBytes, _ := io.ReadAll(r.Body)
Ошибки надо проверять всегда

2024-04-08 15:30 UTC, s-shpak requested changes

2024-04-08 15:30 UTC, s-shpak commented on internal/config/config.go
> +				return fmt.Errorf("expected type string for ServerAddress, received: %T", val)
Но теперь ты потерял ошибку, которую можно обернуть при помощи "%w". Если не очень ясно, как работать с ошибками в го, то возьми 1-1, обсудим

2024-04-08 15:30 UTC, s-shpak commented on internal/middlewares/crypto.go
> +				logger.Error("parsing key error", zap.Error(err))
1. кажется, что текст ошибки должен быть другим
2.  какой ответ придет пользователю, если миддлевер завершится здесь ?

2024-04-08 15:39 UTC, SerjRamone commented on internal/config/config.go
> +				return fmt.Errorf("expected type string for ServerAddress, received: %T", val)
ближайшее возможное время для 1-1 аж в среду. попробую пока сам разобраться. :)

2024-04-11 12:40 UTC, s-shpak approved these changes

2024-04-11 12:40 UTC, s-shpak commented on internal/config/config.go
> +				return fmt.Errorf("expected type string for ServerAddress, received: %T", val)
```go
var errFailedToAssert = "failed to assert type"
...
return fmt.Errorf("%w: expected type string for ServerAddress, received: %T", val)
```

2024-04-11 12:40 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Fatal("reading keyfile error", zap.Error(err))
Стоит вернуть ошибку здесь

2024-04-11 13:24 UTC, merged