Iter25 - gRPC
SerjRamone/metrius pull request #25
Opened 2024-05-15 21:49 UTC by SerjRamone

2024-05-17 15:19 UTC, tmvrus requested changes
- не пробрасывается контекст из входящего запроса
- нет proto-файла
- довольно странное обращение с ошибками в методах grpc

2024-05-17 15:19 UTC, tmvrus commented on cmd/server/main.go
> +		// 	logger.Error("server start error", zap.Error(err))
оставлять закоментированый код в рабочем проекте - дурной тон, это затрудняет его чтение

2024-05-17 15:19 UTC, tmvrus commented on internal/grpc/metrics_server.go
> +	_ = ctx
?

2024-05-17 15:19 UTC, tmvrus commented on internal/grpc/metrics_server.go
> +		response.Error = "unknown metrics type"
зачем изобретать свою ошибку если для нее в сигнатуре уже есть место?

2024-05-17 15:19 UTC, tmvrus commented on internal/grpc/metrics_server.go
> +			break loop
зачем так делать если отсюда сразу можно вернут ошибку?

2024-05-17 15:19 UTC, tmvrus commented on internal/grpc/metrics_server.go
> +	var batch []metrics.Metrics
размер можно указать заранее так как он известен

2024-05-20 21:47 UTC, SerjRamone commented
> * нет proto-файла
api/v1/metrius.proto

2024-05-21 11:29 UTC, tmvrus approved these changes

2024-05-21 11:29 UTC, tmvrus commented on internal/server/server.go
> +	return nil
зачем тут контекст если он не используется?
зачем тут возможность вернуть ошибку, если она не используется?

2024-05-21 11:29 UTC, tmvrus commented on internal/storage/mem.go
> +func (s MemStorage) Gauge(ctx context.Context, name string) (v metrics.Gauge, ok bool) {
Gauge(ctx context.Context, name string) ->  Gauge(_ context.Context, name string)

2024-05-21 11:41 UTC, SerjRamone commented on internal/server/server.go
> +	return nil
> зачем тут контекст если он не используется? зачем тут возможность вернуть ошибку, если она не используется?

а как тут лучше быть? два типа сервера, один из которых этим методом использует контекст и возвращает ошибку, а другой нет.

2024-05-21 13:10 UTC, tmvrus commented on internal/server/server.go
> +	return nil
как минимум можно переписать сигнатуру как (_ context.Context) тогда ненужно будет его использовать внутри ф-и

2024-05-29 19:11 UTC, merged